project:
  type: website
  output-dir: _site

website:
  title: "Wojciech A. Hellwing"
  site-url: "https://hellwing.github.io/hellwing-site/"
  base-url: "/hellwing-site/"

format:
  html:
    theme: cosmo
    toc: true

